remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Ajay Kumar Eeralla
position: Senior Formal Verification Engineer
affiliation: AMD Inc.
email: ajay.eeralla@gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal academic
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=X0-i6YYAAAAJ&hl=en
github_link: https://github.com/ajayeeralla
linkedin: https://www.linkedin.com/in/ajay-kumar-eeralla-phd-b8504219/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
# avatar: ./assets/img/avatar.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4
